name: jsonldConvert
on: [push]
jobs:
  j2q:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g jsonld
      - run: npm install -g jsonld-cli
      - run: ./scripttest1.sh
      - run: git config --global user.email "drfils@gmail.com"
      - run: git config --global user.name "fils"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Committing new files from jsonldConvert run"
      - name: pull from master
        run: git pull --no-rebase origin master
      - name: push code to master
        run: git push origin HEAD:master
