name: processingSet1
on: [push]
jobs:
  val1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install --user rdflib
      - run: pip install --user pyshacl
      - run: python scripts/orgfiles.py -i source/test1.json -o reports/test1_report.rdf
      - run: git config --global user.email "drfils@gmail.com"
      - run: git config --global user.name "fils"
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Committing new files from pySHACL action run"
      - name: pull from master
        run: git pull origin master
      - name: push code to master
        run: git push origin HEAD:master
